### ISSUE TITLE
UI mockups

### ISSUE THREAD

**Issue by rajikaimal** [cloudlibz/nodecloud-web#1]
@amrita019 Please attach the link here.

**Comment by amrita019** [comment]
https://drive.google.com/drive/folders/1bA6UuO9utLlI5yKeXvMZUNQdjSPd0rqz?usp=sharing

**Comment by rajikaimal** [comment]
What I had in mind is a that when you login into the system we'll have a default cloud provider selected eg: AWS, and all the services implemented in the nodecloud-aws-plugin will be available in the UI to interact with. eg: Creating an EC2 instance.

If we want to switch the cloud provider just selecting the another provider (may be using a dropdown in the navigation bar at the top) will change provide the same functionalities since all the plugins implement the same services.

**Comment by amrita019** [comment]
Updated UI mockups: 
https://drive.google.com/drive/folders/1bA6UuO9utLlI5yKeXvMZUNQdjSPd0rqz?usp=sharing

**Comment by amrita019** [comment]
@rajikaimal Is this good to close?

**Comment by rajikaimal** [comment]
Yep
