### ISSUE TITLE
nodecloud-azure-plugin  not found

### ISSUE THREAD

**Issue by TheDhejavu** [cloudlibz/nodecloud-web#18]
I followed the procedure for setting up nodecloud-web but i ran into a few errors listed below

The error below comes from the nodecloud-web server when i tried to run it
Error: Cannot find module 'nodecloud-azure-plugin'

While the error below comes from the npm packag  when i tried to fix the error below.
npm I nodecloud-azure-plugin
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/nodecloud-azure-plugin - Not found

this error is coming from .nc.config.js inside nodecloud

**Comment by amrita019** [comment]
Hello @TheDhejavu 

Thank you for bringing this to notice, this is because the package nodecloud-azure-plugin isn't published yet, for the time being, we can manually add it as a dependency and link it to the project.

Can you go to https://github.com/cloudlibz/nodecloud-azure-plugin and download the project from there and paste it in the node modules.
After that, navigate to that folder via terminal (server > node modules > nodecloud-azure-plugin)
and then hit 
`npm install 
  npm link`

and then try running the project?
Let me know in case you face any other difficulty, I will try to address it as soon as possible.

**Comment by TheDhejavu** [comment]
Thanks @amrita019, I was able to fix that error but i encountered a new errors 

this line seems to be breaking the code
const provider = nodeCloud.getProviders(null)
 nodecloud-web > server > routes > getServices.js

because of the null, the below code returns throws error  inside
 `nodecloud > lib > core > base-provider.js`

options.hasOwnProperty("overrideProviders")

**Comment by JosephSemrai** [comment]
@TheDhejavu I have encountered the same issue where we try to access the `hasOwnProperty` property of `options`, but it has a value of null.
![image](https://user-images.githubusercontent.com/29003194/72025981-f0aa9780-3247-11ea-8d51-6ff704e5ca16.png)

**Comment by TheDhejavu** [comment]
hello @JosephSemrai, this is a major issue in nodecloud and i'm currently working on a fix but for the meantime, paste the code below inside `base-provide.js`, it should fix all of the problems you are currently facing.

```
const path = require("path");
const ncConfig = require(path.join(process.cwd(), ".nc.config"));
const validProviders = require("./providers-list");

class Provider {
  /**
  Provider constructor
  @constructor
  @param {string} provider - Type of provider - can be found here '/aws/provider'
  */
  constructor(options) {
    this._providers = this.getProviders(options);
    return this._providers;
  }
  /**

  Returns requested provider type
  @param {Object} {provider - Type of provider - can be found here '/aws/provider'}
  */
  getProviders(options) {
    if (ncConfig === undefined) {
      throw new Error(
        "Provider config file not found. Please create a config file in project root."
      );
    }
    let providersToLoad = {};
    
      if (options && options.hasOwnProperty("overrideProviders") ) {
        ncConfig.map(provider => {
          const module = provider.plugin;
            providersToLoad[provider.tag] = module(ncConfig.configPath);
          });
      } else {

        ncConfig.map(provider => {
        if (!validProviders.includes(provider.name)) {
          throw new Error("Provider not supported");
        }

      const module = require(provider.libName);
        providersToLoad[provider.tag] = new module(ncConfig.configPath);
      });
    }

    return providersToLoad;
  }
}

module.exports = Provider;
```
