### ISSUE TITLE
Duplicate Styles for login & registration

### ISSUE THREAD

**Issue by TheDhejavu** [cloudlibz/nodecloud-web#36]
The login page has exact styles with the signup page
![nodecloud-web-dup](https://user-images.githubusercontent.com/19678915/73601207-8262a780-455d-11ea-9d61-cda8f017b818.PNG)

**Comment by Vineet-Sharma29** [comment]
@TheDhejavu  Would like to work on this issue. Would it be fine if change folder structure to `auth` such it contains both `login` and `signup` page with a common css?

**Comment by TheDhejavu** [comment]
I have created a fix for this already. I just needed it to be reviewed https://github.com/cloudlibz/nodecloud-web/pull/40 and merged

**Comment by Vineet-Sharma29** [comment]
@TheDhejavu ok!!
